version: '3'

services:
  app:
    build:
      context: .
    container_name: eolass_frontend
    restart: unless-stopped
    working_dir: /usr/src
    volumes:
      - ./:/usr/src
    ports:
      - "5173:5173"
