export enum DotType {
  bouncing = 'bouncing',
  bricks = 'bricks',
  carousel = 'carousel',
  collision = 'collision',
  elastic = 'elastic',
  fire = 'fire',
  flashing = 'flashing',
  floating = 'floating',
  hourglass = 'hourglass',
  overtaking = 'overtaking',
  pulse = 'pulse',
  revolution = 'revolution',
  rolling = 'rolling',
  shuttle = 'shuttle',
  spin = 'spin',
  typing = 'typing',
  windmill = 'windmill',
}
